# ndarray运算

## 逻辑运算

In [2]:
import numpy as np


In [3]:
stock_change = np.random.standard_normal((8, 5))

In [4]:
# 逻辑判断 如果涨跌幅大于0.5就标记为True 否则为False, 对每个元素做相应的逻辑判断
stock_change > 0.5

array([[False,  True,  True, False, False],
       [False, False,  True, False, False],
       [False,  True, False, False,  True],
       [ True, False,  True, False,  True],
       [False, False, False, False, False],
       [ True,  True, False, False, False],
       [False, False, False, False,  True],
       [False, False, False, False,  True]])

In [5]:
# bool索引
temp = stock_change > 0.5
# 取出temp中为true的元素的值
stock_change[temp]

array([1.19941802, 1.95801227, 0.9257031 , 2.23366372, 1.32292056,
       1.66863635, 0.99017492, 0.66821645, 2.04967276, 0.96966268,
       1.72627668, 1.04767313])

In [7]:
stock_change

array([[-0.63820317,  1.19941802,  1.95801227, -0.11892691, -1.2792647 ],
       [-0.4963508 , -2.53621903,  0.9257031 , -0.53433284, -0.15782074],
       [ 0.026423  ,  2.23366372,  0.03567204, -0.63058815,  1.32292056],
       [ 1.66863635, -0.68811214,  0.99017492, -0.77993603,  0.66821645],
       [ 0.0131139 ,  0.23045296,  0.12997876,  0.24422285,  0.20079181],
       [ 2.04967276,  0.96966268, -1.20252316,  0.02729086,  0.29036357],
       [-0.04612226,  0.49240439, -1.40574421, -0.33431744,  1.72627668],
       [-0.0129942 ,  0.12653451, -0.37755406, -1.13288048,  1.04767313]])

In [11]:
stock_change[0:2, :]

array([[-0.63820317,  1.19941802,  1.95801227, -0.11892691, -1.2792647 ],
       [-0.4963508 , -2.53621903,  0.9257031 , -0.53433284, -0.15782074]])

In [12]:
# 判断stock_change[0:2, 0:5]是否全是上涨的
np.all(stock_change[0:2, 0:5] > 0)

False

In [14]:
# 判断前5只股票这段期间是否有上涨的
np.all(stock_change[:5, :] > 0)

False

In [16]:
# 判断前四个股票前四天的涨跌幅 大于0的置为1，否则为0
temp = stock_change[:4, :4] > 0
np.where(temp, 1, 0)

array([[0, 1, 1, 0],
       [0, 0, 1, 0],
       [1, 1, 1, 0],
       [1, 0, 1, 0]])

In [18]:
# 判断前四个股票前四天的涨跌幅 大于0.5或者小于-0.5的，换为1，否则为0
temp = np.logical_or(stock_change[:4, :4] > 0.5, stock_change[:4, :4] < -0.5)
np.where(temp, 1, 0)

array([[1, 1, 1, 0],
       [0, 1, 1, 1],
       [0, 1, 0, 1],
       [1, 1, 1, 1]])

## 统计运算

In [19]:
# 前四只股票前四天的最大涨幅
statistics_data = stock_change[:4, :4]
# 求每一行的最大值
np.max(statistics_data, axis=1)

array([1.95801227, 0.9257031 , 2.23366372, 1.66863635])

In [20]:
# 求每一行的中位数
np.median(statistics_data, axis=1)

array([ 0.54024556, -0.51534182,  0.03104752,  0.15103139])

In [21]:
# 求每一行最大值的下标
np.argmax(statistics_data, axis=1)

array([2, 2, 1, 0], dtype=int64)

## 数组运算

In [32]:
arr = np.array([[1, 2, 3, 4, 5, 6], [6, 5, 4, 3, 2, 1]])
# 数组与标量的运算  每个元素进行对应的加减乘除
arr = arr - 2
arr

array([[-1,  0,  1,  2,  3,  4],
       [ 4,  3,  2,  1,  0, -1]])

In [33]:
arr_2 = np.linspace(1, 12, 12).reshape((2, 6))
arr_2

array([[ 1.,  2.,  3.,  4.,  5.,  6.],
       [ 7.,  8.,  9., 10., 11., 12.]])

In [34]:
arr + arr_2

array([[ 0.,  2.,  4.,  6.,  8., 10.],
       [11., 11., 11., 11., 11., 11.]])

In [35]:
arr_3 = np.array([[4], [6]])
arr_3

array([[4],
       [6]])

In [36]:
arr + arr_3

array([[ 3,  4,  5,  6,  7,  8],
       [10,  9,  8,  7,  6,  5]])

In [39]:
arr_4 = np.array([1, 2, 3, 4, 5, 6])
arr_4

array([1, 2, 3, 4, 5, 6])

In [40]:
arr + arr_4

array([[ 0,  2,  4,  6,  8, 10],
       [ 5,  5,  5,  5,  5,  5]])

## 矩阵乘法

In [41]:
score = [[80, 86],
         [82, 80],
         [85, 78],
         [90, 90],
         [86, 82],
         [82, 90],
         [78, 80],
         [92, 94]]

score = np.array(score)
score

In [42]:
# 矩阵权重
w = np.array([[0.3], [0.7]])
# 矩阵乘法
np.matmul(score, w)

array([[84.2],
       [80.6],
       [80.1],
       [90. ],
       [83.2],
       [87.6],
       [79.4],
       [93.4]])

In [43]:
np.dot(score, w)

array([[84.2],
       [80.6],
       [80.1],
       [90. ],
       [83.2],
       [87.6],
       [79.4],
       [93.4]])

In [44]:
# 可以进行矩阵和标量的乘法
np.dot(score, 10)

array([[800, 860],
       [820, 800],
       [850, 780],
       [900, 900],
       [860, 820],
       [820, 900],
       [780, 800],
       [920, 940]])